[tool.ruff.lint]
extend-select = ["B"]
[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true